### ISSUE TITLE
Up-sorting elements isn't triggering 

### ISSUE THREAD

**Issue by mydudechris** [rkusa/touch-dnd#38] opened 2015-06-05 15:30 UTC
### Video
http://cl.ly/3E0w0u2m2d1p

### Description
- Creating a list of _complex_ LI elements via ajax request
- I enable dnd for the list elements after it's been appended to the page
- Ex: 
```javascript
    function enableDnD (elem, connectWith) {
        $(elem).sortable({
            items: 'li.dragItem',
            placeholder: 'dummy',
            forcePlaceholderSize: true,
            connectWith: '.' + connectWith,
            handle: '.li_ctrl-move'
        }).on('sortable:start', function(e, ui) {
            ui.item.addClass('draggable');
        }).on('sortable:stop', function(e, ui) {
            ui.item.removeClass('draggable');
        }).on('sortable:update', function(e, ui) {
    });
    }
```
- elem is for the parent ul and connectWith is for a list that I can sort elements to. 
- Dragging elements down seems to work fine
- Dragging those same elements up 
-- Requires that I drag them _way_ above the next element to register
-- Won't allow me to replace the first element in the list

### Troubleshooting
- I've tried removing all styles down, same behavior
- I've tried changing all kinds of styles and html, from removing display:flex to changing the structure from ul>li>ul>li to ul>li>div, same behavior

**Comment by rkusa** [comment] 2015-06-05 16:02
Thanks for reporting! I am not able to reproduce this issue :-/
Could you send me an example page with the html/css structure your are using? (e.g. to the email address from my github profile)

**Comment by mydudechris** [comment] 2015-06-05 16:04
Sure thing, give me a few mins to scrub/package it up.

**Comment by mydudechris** [comment] 2015-06-05 16:15
@rkusa email sent, page uploaded here: http://christate.is/designing/dnd/app/

**Comment by rkusa** [comment] 2015-06-05 16:40
Should be fixed. Please let me know if it works now.
Thanks

**Comment by mydudechris** [comment] 2015-06-05 16:45
OMG you're the man! Can I buy you a 🍻or ☕? Yes, fixed.

**Closed** 2015-06-05 16:52 UTC

**Comment by rkusa** [comment] 2015-06-07 10:37
Your good issue explanation and example html/css setup helped solving a issue easily and thereby helped making `touch-dnd` better. So I have to thank you, no :beers: or :coffee: required, but thanks for the intent :-)
