### ISSUE TITLE
Bugs with sortable on the last version

### ISSUE THREAD

**Issue by PhilipGarnero** [rkusa/touch-dnd#19] opened 2015-01-23 03:46 UTC
Hello there !  
First, let me thank you for this wonderful plugin,
you've done a wonderful job !  
I'm using `sortable` to let the user sort a list of elements but I was having bugs with the selected element as it was still taking space in the list when dragged instead of just being replaced by the placeholder.
I also had an issue in which when I drop the element (still in sortable) both the element and the placeholder would disappear.  
Here's my code and in case you're wondering, `#level-list` is a simple `ul` containing some `li`
```
$(document).ready(function() {
    $('#level-list').sortable().on('sortable:update', function(e, ui) {
        console.log("cool !");
    })
})
```
I was confused because the example on your site is working well and I figured out the script used on the site is an older version. After giving it a try everything worked as expected.

**Comment by rkusa** [comment] 2015-01-23 06:07
Hi @PhilipGarnero, thanks for reporting your issue!

> as it was still taking space in the list when dragged instead of just being replaced by the placeholder.

Is it maybe the placeholder that takes up the place but has no placeholder specific style applied to it?

> I also had an issue in which when I drop the element (still in sortable) both the element and the placeholder would disappear.

Should be fixed.

I'll update the github pages to use the most recent version.

Please let me know if the issue is resolve for you, thanks!

**Comment by PhilipGarnero** [comment] 2015-01-23 15:49
Good job for the "disappear" bug, it's gone.

Should I apply special styles for the placeholder ?
Currently I've just set height width and bg-color.
On the image, you can see the sortable elements in grey and the placeholder in red.
There is a white square corresponding to the flying square which is not present in the older version.
![placeholder-bug](https://cloud.githubusercontent.com/assets/5165169/5876382/07e9e236-a317-11e4-95e4-1ce8141e40bc.png)

One more question, I have buttons with the onclick attribute set in the sortable elements but they're not being triggered as the event is being intercepted by your script. What should I do to keep my onclick ? I tried the stopPropagation but then you can't drag elements anymore.

**Comment by rkusa** [comment] 2015-01-23 16:07
Is it possible that you share your code (or the relevant subset of it)?

**Comment by PhilipGarnero** [comment] 2015-01-23 16:26
My code is pretty simple :
```
<style type="text/css">
ul#level-list {
    li {
        height: 100px;
        width: 100px;
        background-color: grey;
        &.placeholder {
            background-color: red;
        }
    }
}
</style>
<script type="text/javascript">
function assign_index() {
    $("#level-list>li:not(.placeholder)").each(function(index) {
        $(this).attr("data-offset", index + 1);
    });
}
$(document).ready(function() {
    assign_index();
    $('#level-list').sortable().on('sortable:update', function(e, ui) {
        assign_index();
    })
})
</script>
<div class="row">
    <div class="small-12">
        <ul id="level-list" class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
            <li data-offset="1">1
                <a href="#" onclick="ajax_function(); return false;"><i class="size-24 fi-pencil"></i></a>
                <a href="#" onclick="ajax_function(); return false;"><i class="size-24 fi-trash"></i></a>
            </li>
            <li data-offset="2">2
                <a href="#" onclick="ajax_function(); return false;"><i class="size-24 fi-pencil"></i></a>
                <a href="#" onclick="ajax_function(); return false;"><i class="size-24 fi-trash"></i></a>
            </li>
            <li data-offset="3">
                <a href="#" onclick="ajax_function(); return false;"><i class="size-24 fi-plus"></i></a>
            </li>
        </ul>
    </div>
</div>
```

**Comment by rkusa** [comment] 2015-01-23 17:38
I think it is related to display: inline-block. You are using inline-block, aren't you? (Neither that nor float left is contained in the snippet)

**Comment by PhilipGarnero** [comment] 2015-01-23 17:57
I'm using `display: block;` but It was perfectly fine with the previous version.
Concerning the click event being intercepted, do you have any idea ?

**Comment by rkusa** [comment] 2015-01-23 18:30
The option `cancel: 'a'` should fix the link problem

**Comment by PhilipGarnero** [comment] 2015-01-23 18:33
Marvelous !
You should put details like this in your readme.
Truly amazing work !

**Comment by rkusa** [comment] 2015-01-25 00:55
I'll make the links on ma.rkusa.st/touch-dnd (to e.g. http://ma.rkusa.st/touch-dnd/sortable.html) more obvious :-)

**Closed by rkusa** 2015-01-25 00:55 UTC
